id: P009299
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3408
  title: སྤྱོད་འཇུག་གི་རྣམ་པར་བཤད་པ་སོགས་འགྲེལ་པ་ཁག་ཅིག
  author: ''
  volumes:
    f36c66f8793e45baa2bc15b24e858fd3:
      image_group_id: I1KG3497
      title: ''
      volume_number: 1
      total_pages: 1736
      base_file: v001.txt
